version: '3.8'

services:
  siges-frontend:
    image: siges:latest
    container_name: siges_frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - TZ=America/Lima
    networks:
      - stack_net
      - data_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  stack_net:
    external: true
    name: stack_stack_net
  data_net:
    external: true
